Update: Variants and Fixed: Bugs
tailwindcss-tw/tailwindcss.com pull request #103
Opened 2021-05-22 05:12 UTC by beibei0221

2021-05-23 08:48 UTC, ashramwen requested changes

2021-05-23 08:48 UTC, ashramwen commented on src/pages/docs/configuring-variants.mdx
> +每個屬性都是一個核心插件名稱，指向要為該插件產生的變化模式陣列。
太過直翻，有點不太通順

2021-05-23 08:48 UTC, ashramwen commented on src/pages/docs/configuring-variants.mdx
> +這意味著，給定以下 HTML：
這有點奇妙... 只看句子會不太懂意思

2021-05-23 08:48 UTC, ashramwen commented on src/pages/docs/configuring-variants.mdx
> +這是因為 `responsive` 變化模式會自動與其他變化模式 _堆疊_ 在一起，這意味著如果你為一個功能指定了  `responsive` 和 `hover` 變化模式，Tailwind 也會產生 _responsive hover_ 變化模式。
`responsive` 前面多空了一格

2021-05-23 15:18 UTC, beibei0221 commented on src/pages/docs/configuring-variants.mdx
> +每個屬性都是一個核心插件名稱，指向要為該插件產生的變化模式陣列。
@ashramwen 調整成：每個屬性都是一個核心插件名稱，以陣列形式指定要為該插件產生的變化模式？

2021-05-23 15:18 UTC, beibei0221 commented on src/pages/docs/configuring-variants.mdx
> +這意味著，給定以下 HTML：
@ashramwen 這句要和下方的第180和184行一起看才會完整 > <

2021-05-23 15:58 UTC, ashramwen commented on src/pages/docs/configuring-variants.mdx
> +每個屬性都是一個核心插件名稱，指向要為該插件產生的變化模式陣列。
good
後面的那個 `要` 有點多餘

2021-05-23 16:01 UTC, ashramwen commented on src/pages/docs/configuring-variants.mdx
> +這意味著，給定以下 HTML：
```
這會產生下列 HTML：
```

這樣就好了，語意比較重要

2021-05-23 16:03 UTC, ashramwen commented on src/pages/docs/configuring-variants.mdx
> +這意味著，給定以下 HTML：
```
這會產生下列 HTML：
```

這樣就好了，語意比較重要

2021-05-24 09:32 UTC, ashramwen approved these changes

2021-05-24 09:32 UTC, merged