Update: text-align
tailwindcss-tw/tailwindcss.com pull request #105
Opened 2021-05-23 09:15 UTC by ezcomenezgo

2021-05-23 15:06 UTC, ashramwen commented on src/pages/docs/text-align.mdx
> +title: "Text Alignment" (文字對齊)
雙引號在我這邊 compile 會失敗耶，拿掉才正常，你可以正常編譯?

2021-05-23 15:37 UTC, ashramwen requested changes

2021-05-23 15:37 UTC, ashramwen commented on src/pages/docs/text-align.mdx
> +title: "Text Alignment" (文字對齊)
雙引號在我這邊 compile 會失敗耶，拿掉才正常，你可以正常編譯嗎 ?

2021-05-23 15:42 UTC, ashramwen requested changes

2021-05-23 15:42 UTC, ashramwen commented on src/pages/docs/text-align.mdx
> +title: "Text Alignment" (文字對齊)
雙引號要把後面的內容也包含進去，不然編譯不會過

![image](https://user-images.githubusercontent.com/3334950/119267297-7ef6a200-bc20-11eb-9717-3ce54645cb72.png)

2021-05-23 18:08 UTC, ezcomenezgo commented on src/pages/docs/text-align.mdx
> +title: "Text Alignment" (文字對齊)
本地的檔案已經修改完畢了，但是不好意思，我在push的過程遇到問題了QQ
原本照著操作流程在修改完之後接 _4. 翻譯完成後 將檔案推送回 git_ 裡面的步驟
結果出現 rejected，閱讀完錯誤訊息應該是我現在的分支落後遠端的分支，應該要先 git pull 整合
後來有試著 pull 下來，再推一次但還是出現一樣的錯誤訊息，不過我不敢亂用很怕用壞...
請問我是哪邊出錯了呢？
![image](https://user-images.githubusercontent.com/75515395/119271490-5ed0de00-bc34-11eb-9600-146424d3a4e4.png)

2021-05-24 09:27 UTC, ashramwen commented on src/pages/docs/text-align.mdx
> +title: "Text Alignment" (文字對齊)
第一段 rebase 的錯誤訊息我有點不解，因為我這邊測試是正常的
有 commit graph 可以看一下嗎?

2021-05-24 10:09 UTC, ezcomenezgo commented on src/pages/docs/text-align.mdx
> +title: "Text Alignment" (文字對齊)
有哦!! 再麻煩可樂大幫忙看看，謝謝!!!
![image](https://user-images.githubusercontent.com/75515395/119332403-1b6d8280-bcbb-11eb-811a-932bf60c8b3c.png)

2021-05-25 05:37 UTC, ashramwen approved these changes

2021-05-25 05:37 UTC, merged