Feature: add docs screen readers
tailwindcss-tw/tailwindcss.com pull request #110
Opened 2021-05-23 16:41 UTC by kayac-chang

2021-05-24 09:54 UTC, beibei0221 reviewed
英文的標點符號需要改成中文的嗎？

2021-05-25 05:20 UTC, ashramwen commented
> 英文的標點符號需要改成中文的嗎？

要，period 和 colon 也要全形的

2021-05-25 05:26 UTC, ashramwen requested changes

2021-05-25 05:26 UTC, ashramwen commented on src/pages/docs/screen-readers.mdx
> +使用 `not-sr-only` 可以復原 `sr-only`，讓元素可以被使用者跟螢幕報讀機判讀. 這便於當你想要在小螢幕時，在視覺上的隱藏某個元件，但是在大螢幕要顯示的情況，舉個例子:
`. ` 這要換成 `，`
還有最後面的 colon

2021-05-25 05:26 UTC, ashramwen commented on src/pages/docs/screen-readers.mdx
> +預設情況下，`responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏，但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
逗號和冒號全形

2021-05-25 05:26 UTC, ashramwen commented on src/pages/docs/screen-readers.mdx
> +description: "提升螢幕報讀機之無障礙功能的工具"
Utilities 我們翻成功能

2021-05-25 05:26 UTC, ashramwen commented on src/pages/docs/screen-readers.mdx
> +預設情況下，`responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏，但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
utilities -> 功能

2021-05-25 05:26 UTC, ashramwen commented on src/pages/docs/screen-readers.mdx
> +預設情況下，`responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏，但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
tab 前後要空格

2021-05-25 13:29 UTC, huibizhang commented on src/pages/docs/screen-readers.mdx
> +預設情況下, `responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏, 但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
"tab" -> " tab "

不過我有點不太懂「利於 "前往內容" 連結」是甚麼意思
skip to content 這件是在無障礙功能上代表甚麼？

2021-05-25 13:30 UTC, huibizhang commented on src/pages/docs/screen-readers.mdx
> +預設情況下，`responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏，但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
其實我不是很能理解 skip to content 在無障礙中代表甚麼功能

2021-05-31 05:27 UTC, kayac-chang commented on src/pages/docs/screen-readers.mdx
> +預設情況下，`responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏，但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
fixed

2021-05-31 05:27 UTC, kayac-chang commented on src/pages/docs/screen-readers.mdx
> +description: "提升螢幕報讀機之無障礙功能的工具"
fixed

2021-05-31 05:28 UTC, kayac-chang commented on src/pages/docs/screen-readers.mdx
> +使用 `not-sr-only` 可以復原 `sr-only`，讓元素可以被使用者跟螢幕報讀機判讀. 這便於當你想要在小螢幕時，在視覺上的隱藏某個元件，但是在大螢幕要顯示的情況，舉個例子:
fixed

2021-05-31 05:30 UTC, kayac-chang commented on src/pages/docs/screen-readers.mdx
> +預設情況下，`responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏，但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
> 其實我不是很能理解 skip to content 在無障礙中代表甚麼功能

reference to [WebAIM: "Skip Navigation" Links](https://webaim.org/techniques/skipnav/)

2021-05-31 05:30 UTC, kayac-chang commented on src/pages/docs/screen-readers.mdx
> +預設情況下，`responsive` 跟 `focus` 會生成這個工具. 你可以透過使用 `focus:not-sr-only` 讓元素在預設的情況隱藏，但在使用者tab到該元素時顯示 - 尤其利於 "前往内容" 連結:
fixed

2021-05-31 13:05 UTC, huibizhang approved these changes

2021-06-01 02:07 UTC, merged