Update: align-content.mdx
tailwindcss-tw/tailwindcss.com pull request #31
Opened 2021-04-13 15:58 UTC by CXPhoenix

2021-04-13 16:34 UTC, ashramwen requested changes
https://codepen.io/ashramwen/pen/poRLqVp
align 和 justify 的對齊方向都會受到 `flex-direction` 的影響，所以不適合直接打上水平或垂直

2021-04-13 16:34 UTC, ashramwen commented on src/pages/docs/align-content.mdx
> +### 變化模式
@huibizhang 這個後來有確定中文翻譯了嗎?

2021-04-16 10:01 UTC, huibizhang commented
> https://codepen.io/ashramwen/pen/poRLqVp
> align 和 justify 的對齊方向都會受到 `flex-direction` 的影響，所以不適合直接打上水平或垂直

@ashramwen 所以這個你目前有任何想法嗎？ 保持英文？

2021-04-20 02:51 UTC, ashramwen commented
> > https://codepen.io/ashramwen/pen/poRLqVp
> > align 和 justify 的對齊方向都會受到 `flex-direction` 的影響，所以不適合直接打上水平或垂直
> 
> @ashramwen 所以這個你目前有任何想法嗎？ 保持英文？

保持英文吧

2021-04-20 02:53 UTC, huibizhang commented
> > > https://codepen.io/ashramwen/pen/poRLqVp
> > > align 和 justify 的對齊方向都會受到 `flex-direction` 的影響，所以不適合直接打上水平或垂直
> > 
> > 
> > @ashramwen 所以這個你目前有任何想法嗎？ 保持英文？
> 
> 保持英文吧

OK~~

2021-12-20 16:17 UTC, closed without merging