Updated some of Installation and Utilty-First. Bug fixed on Index and some components.
tailwindcss-tw/tailwindcss.com pull request #32
Opened 2021-04-13 23:02 UTC by huibizhang

Updated some of Installation and Utilty-First. Bug fixed on Index and some components.

2021-04-14 07:23 UTC, ashramwen commented
branch 要改成 tw

2021-04-15 02:23 UTC, ashramwen requested changes

2021-04-15 02:23 UTC, ashramwen commented on src/pages/docs/installation.mdx
> +  <ListItemBad>無法在打包時將沒使用到的樣式忽略</ListItemBad>
`tree shaking` 建議直接保留英文，或是用括號註解

2021-04-15 02:23 UTC, ashramwen commented on src/pages/docs/installation.mdx
> +如果想要快速的 demo 一下 Tailwind，或是想測試一下這個框架，你可以用 CDN 來取得最新的預設配置：
`demo` 不翻嗎? 很單純的英文，翻成 "玩耍" ?

2021-04-15 02:23 UTC, ashramwen commented on src/pages/docs/installation.mdx
> +  請注意一下，CDN 版是很大的 ( 壓縮後 71.5kB, 原始大小 3020.9kB )。**但這不代表用安裝的方式使用 Tailwind，還會是這個大小。**
意思有點微妙，原文的意思是 **這並不代表(或等同於) 使用 Tailwind 建置後的檔案大小**

2021-04-15 02:23 UTC, ashramwen commented on src/pages/index.js
> +                  <span className="hidden sm:inline">繁中文件</span>
技術文件

2021-04-15 02:23 UTC, ashramwen commented on src/pages/index.js
> +                  <span className="hidden sm:inline">官方網站</span>
EN

2021-04-15 02:23 UTC, ashramwen commented on src/pages/index.js
> +                  就為了說明「為什麼傳統語義類 class 名稱的 CSS 會這麼難維護」這件事，但事實上，如果你沒有親自嘗試過，你永遠不會相信我。只要你願意耐心的給它一個機會，我相信你絕對會想知道怎麼透過其他的方式使用 CSS。
我用 `{'xxx'}` 包起來是避免被 IDE 斷行，而在網頁上產生空白，或在不正確的地方斷行

2021-04-15 02:23 UTC, ashramwen commented on src/pages/docs/installation.mdx
> +如果想要 Tailwind的完整功能，你應該要 [以 PostCSS 插件的方式來安裝 Tailwind CSS]
Tailwind 前後空格

2021-04-15 02:23 UTC, ashramwen commented on src/pages/docs/installation.mdx
> +這時候會產生一個預設值的 tailwind配置檔 `tailwind.config.js` 在你的專案根目錄：
tailwind 大寫加空白?
或是乾脆別放 tailwind

2021-04-15 02:23 UTC, ashramwen commented on src/pages/docs/installation.mdx
> +Tailwind CSS 的安裝過程可能會因為你所使用的框架(frameworks)或工具(tools)不同而有些微差異，所以這邊整合了在幾個熱門框架上及工具中安裝 Tailwind CSS 的方法。
(frameworks) 和 (tools) 前後空白?

2021-04-15 02:59 UTC, huibizhang commented on src/components/home/BuildAnything.js
> +          <Widont>你能創造你想要的一切，沒唬爛你</Widont>
好，已修正

2021-04-15 03:05 UTC, huibizhang commented on src/pages/docs/installation.mdx
> +如果想要快速的 demo 一下 Tailwind，或是想測試一下這個框架，你可以用 CDN 來取得最新的預設配置：
我想想，可是一般我們口語的時候不是也會講 ***做個demo版*** 之類的嗎?

2021-04-15 03:06 UTC, huibizhang commented on src/pages/docs/installation.mdx
> +  請注意一下，CDN 版是很大的 ( 壓縮後 71.5kB, 原始大小 3020.9kB )。**但這不代表用安裝的方式使用 Tailwind，還會是這個大小。**
OK，我改掉了

2021-04-15 03:11 UTC, huibizhang commented on src/pages/docs/installation.mdx
> +Tailwind CSS 的安裝過程可能會因為你所使用的框架(frameworks)或工具(tools)不同而有些微差異，所以這邊整合了在幾個熱門框架上及工具中安裝 Tailwind CSS 的方法。
這是我最當初寫的，沒改到，感謝

2021-04-15 03:11 UTC, huibizhang commented on src/pages/docs/installation.mdx
> +這時候會產生一個預設值的 tailwind配置檔 `tailwind.config.js` 在你的專案根目錄：
不要放好像比較好

2021-04-15 03:54 UTC, ashramwen requested changes

2021-04-15 03:54 UTC, ashramwen commented on src/pages/docs/installation.mdx
> +在用 CDN 引入之前請注意，因為 Tailwind 有很多特色功能是必須要安裝才能使用=的，如果要用CDN方式使用 Tailwind，需要稍微留意一下下面幾點：
多了一個 =

2021-04-15 03:55 UTC, huibizhang commented on src/pages/docs/installation.mdx
> +在用 CDN 引入之前請注意，因為 Tailwind 有很多特色功能是必須要安裝才能使用=的，如果要用CDN方式使用 Tailwind，需要稍微留意一下下面幾點：
居然沒刪到...，感謝

2021-04-15 04:01 UTC, ashramwen approved these changes

2021-04-15 04:01 UTC, merged