feat: 🎸 Translate 'Responsive Design' page
tailwindcss-tw/tailwindcss.com pull request #49
Opened 2021-04-16 18:12 UTC by kevinshu1995

2021-04-17 02:34 UTC, huibizhang commented on src/pages/docs/responsive-design.mdx
> +### 定位行動裝置
這樣翻感覺怪怪的

2021-04-17 02:34 UTC, huibizhang commented on src/pages/docs/responsive-design.mdx
> +<TipBad>不要使用 <code className="text-sm font-bold text-gray-800">sm:</code> 來定位行動裝置</TipBad>
這邊也是，和上面同一句

2021-04-17 02:34 UTC, huibizhang commented on src/pages/docs/responsive-design.mdx
> +<TipGood>使用沒有前綴詞的功能來定位手機，並在較大的斷點覆蓋它們</TipGood>
這裡也是

2021-04-17 02:34 UTC, huibizhang commented on src/pages/docs/responsive-design.mdx
> +### 定位單一斷點
感覺還可以翻得更好， 我想想，但感覺能更通順

2021-04-17 03:39 UTC, ashramwen requested changes
- 您->你
- 英文在前，中文在後
- title順序調整

2021-04-17 03:39 UTC, ashramwen commented on src/pages/docs/responsive-design.mdx
> +title: 響應式設計 (Responsive Design)
昨天臨時提議，大家決定把英文放前面，中文放後面，然後不用括號

2021-04-17 03:39 UTC, ashramwen commented on src/pages/docs/responsive-design.mdx
> +<!-- To add a utility but only have it take effect at a certain breakpoint, all you need to do is prefix the utility with the breakpoint name, followed by the `:` character: -->
上面這一段排版有點亂，雖然畫面上沒問題，但會讓開發的人看得不太清楚
你可以這樣就好
![image](https://user-images.githubusercontent.com/3334950/115100390-e315ae80-9f6e-11eb-9e3d-fc650fa9fa7d.png)

只註解掉第一行 table header
下面的 breakpoints 不用也備份然後註解一次

2021-04-17 03:39 UTC, ashramwen commented on src/pages/docs/responsive-design.mdx
> +<!-- ```html indigo
這邊也不用整段註解，只要這樣即可
![image](https://user-images.githubusercontent.com/3334950/115100578-1dcc1680-9f70-11eb-92f1-bb541633d78b.png)
中文英文相差太遠，就很難中英對照了

2021-04-17 03:39 UTC, ashramwen commented on src/pages/docs/responsive-design.mdx
> +<!-- ```html indigo
附帶一提，因為這裡的是案例分享
在這案例中的"您"有特別意義，因為是要提供客戶服務
所以我覺得這裡用"您"是ok的，應該說你或您都可以

2021-04-18 03:32 UTC, huibizhang commented on src/pages/docs/responsive-design.mdx
> +如果你只想在某個斷點上應用某項功能，只需要在更大的斷點上新增另一個的功能，藉此來*抵銷*前一項功能的效果。
目前翻「抵銷」是可以的。但有沒有要改「覆蓋」就看你
如果有要改，就改完之後再 push 一次，
如果沒有要改，就回覆我說不改
我就要開始合進去了~~~~~

2021-04-18 03:58 UTC, kevinshu1995 commented on src/pages/docs/responsive-design.mdx
> +如果你只想在某個斷點上應用某項功能，只需要在更大的斷點上新增另一個的功能，藉此來*抵銷*前一項功能的效果。
我不改啦!
麻煩了謝謝~

2021-04-18 04:09 UTC, huibizhang approved these changes

2021-04-18 04:09 UTC, huibizhang approved these changes

2021-04-18 04:10 UTC, merged