finish customizing-spacing
tailwindcss-tw/tailwindcss.com pull request #87
Opened 2021-05-01 13:30 UTC by beareatapple

2021-05-01 16:22 UTC, ashramwen requested changes

2021-05-01 16:22 UTC, ashramwen commented on src/pages/docs/customizing-spacing.mdx
> +這將會禁用 Tailwind 裡預設的間距設定，並且建立 `p-sm`, `m-md`, `w-lg` 和 `h-xl` 的 class 取代原有的設定。
, 

這邊應該要用、

```
並且建立 `p-sm`、`m-md`、`w-lg` 和 `h-xl` 的 class 取代原有的設定。
```

2021-05-01 16:22 UTC, ashramwen commented on src/pages/docs/customizing-spacing.mdx
> +這將會增加 `p-13`, `m-15`, 和 `h-128` 的 class 到 Tailwind 的預設間距/尺寸功能裡。
```
這將會增加 `p-13`、`m-15` 和 `h-128` 的 class
```

2021-05-01 16:22 UTC, ashramwen commented on src/pages/docs/customizing-spacing.mdx
> +在預設情況下，間距大小會被 `padding`, `margin`, `width`, `height`, `maxHeight`, `gap`, `inset`, `space`, 和 `translate` 等核心插件繼承。
```
間距大小會被 `padding`、`margin`、`width`、`height`、`maxHeight`、`gap`、`inset`、`space` 和 `translate` 等核心插件繼承。
```

2021-05-01 16:22 UTC, ashramwen commented on src/pages/docs/customizing-spacing.mdx
> +在 `tailwind.config.js` 檔案裡的 `theme` 使用 `spacing` 來指定 Tailwind 的 [預設間距/尺寸 大小](#default-spacing-scale)。
[預設間距/尺寸 大小]
這是故意空格的嗎?

2021-05-02 01:32 UTC, beareatapple commented on src/pages/docs/customizing-spacing.mdx
> +在 `tailwind.config.js` 檔案裡的 `theme` 使用 `spacing` 來指定 Tailwind 的 [預設間距/尺寸 大小](#default-spacing-scale)。
是的，想說大小是間距跟尺寸共用的名詞，不過空格似乎怪怪的呴，我還是把它接回去好了，謝謝。

2021-05-02 06:56 UTC, ashramwen approved these changes

2021-05-02 06:56 UTC, merged